### ISSUE TITLE
Sprite container/shapes are duplicated needlessly

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#1368]
We had code that should've made these two shapes in the Ogre Brawler identical:

```
{"t":[33.6,31.5],"p":"ABVFxQiQgbhKhKQj5kKgLiOQgIiAAyg2QA+hCCtALIAyALQA/AsBRBKQCkCVBeCYQAVAgAPAgQANAbACAMQAUBRgcA6QgZAzg1ATQguAPg7AAQgzAAg8gLg","fc":"#91B1CE"}
{"t":[21.8,20.3],"p":"ABVFxQiQgbhKhKQj5kKgLiOQgIiAAyg2QA+hCCtALIAyALQA/AsBRBKQCkCVBeCYQAVAgAPAgQANAbACAMQAUBRgcA6QgZAzg1ATQguAPg7AAQgzAAg8gLg","fc":"#91B1CE"}
```

But it's not working, maybe because the transform is different? There's a similar problem for containers, where the same R_Leg piece is in there four times. This is probably making things a lot bigger than they need to be.

**Comment by sderickson** [comment]
I tested factoring out transforms to be in 'local shape' data instead of the shape store, and imported ogre brawler fore and back animations, and the raw animation data actually became larger (probably because the container shape list became a list of objects instead of a list of strings, so that it could include both the shape global name and transform data). The raw data size went from 68,838 to 69,236. When I zipped the data, it flipped slightly: 29,813 -> 29,368. Doesn't seem to make much of a difference either way.
