### ISSUE TITLE
Level Achievements are not working

### ISSUE THREAD

**Issue by JeroenTondeleir** [codecombat/codecombat#1780]
The achievement system is not working, so when you have completed a level or more you don't get the achievement.  [Picture of bug](http://prntscr.com/592q7c)

**Comment by earendil-the-mariner** [comment]
Hey there, I have a similar problem, none of the achievements except the signup:
![image](https://cloud.githubusercontent.com/assets/4030090/5604635/8e152062-937e-11e4-8f6c-5edf1d080bf5.png)

Perhaps the level achievements could be rewarded retroactively by making them rewards for beating specific levels, rather than a set number of levels.

**Comment by nwinter** [comment]
- [x] Finish debugging the memory leak fix reenablement of doc init tracking
- [ ] Look for the repeatable proportionalTo bug in recalculation (write a test maybe)
- [ ] Make sure all achievement server tests
- [ ] Run a script to run the achievement plugin post-save logic on everyone (and maybe non-user models, too, if there are any relevant achievements)
- [ ] Recalculate achievements once everything is working and said script is done

**Comment by nwinter** [comment]
The remaining bug is that increments to things like a user's `stats.gamesPlayed` goes through an update `$inc` operation, not a normal save, so the AchievementPlugin's post-save hook never fires. I can now recalculate them with scripts, but they won't take dynamically.

**Comment by nwinter** [comment]
Fixed in 87f3b9e.
