### ISSUE TITLE
Tile is Traversable or Tile has Obstacle

### ISSUE THREAD

**Issue by sotonin** [codecombat/codecombat#1963]
It would be nice to have a method that helps to create pathfinding algorithms by telling the user if a specific tile (x, y) is walkable. 

If could be done a few ways, doesn't matter too much the 2 possible options I can envision are as follows:

1. this.hasObstacle(x, y)
    If there is a house, fence, tree, etc at that coord (player can not physically step on the tile) then it would return true otherwise false.

2. this.isWalkable(x, y)
    This could possibly integrate into the built in pathfinding system, where x, y is where you wish to end up and it calculates through the same as moveXY but detects if you will end up against an obstacle with "i can not reach there" message. It shouldn't actually move you, just return a true or false. Option 1 is much easier imo and should be just fine.

**Comment by nwinter** [comment]
Proposed API:

`isPathClear(pos1, pos2)`: returns whether there are any obstacles (including walls, cliffs, houses, boulders, doors, etc.) or hazards (fire-trap, bear-traps, spike walls, pits, lava flows, etc.) between pos1 and pos2, inclusive.

`findHazards`: returns a list of hazards, visible or not.

This wouldn't let you query for all obstacles, since there are a lot of them, it'd be slow, and the obstacles are often not what you'd expect (like when we use Invisible Obstacle 3 instead of 6 cliffs). But it would let you do your own bits of pathfnding, and it would let you check for traps.

Comments?

**Comment by J-F-B-M** [comment]
My remark:

`isPathClear(pos1, pos2)`: Does this mean there is a straight path, or that pathing is possible without encountering any hazards? I would reduce it to just obstacles, limit it to straight lines and let the players manage the hazards himself. 

`findHazards`: Returns a list with all currently visible hazards, as with the enemies. If the player wants to remember a currently not visible trap he has seen in the past, he has to save it somehow. In a complex multiplayer-levels with walls that block line-of-sight and movement, information can get old (except with the best glasses) (I'm imagianing possibilities here).

Querrying every Thang is really not the best thing as described. But for the Thangs one can get, can you somehow get the dimensions of it? It is one thing to know there is a pit at (12,34), but another one to know that it reaches from (10,32) to (14,36).

**Comment by sotonin** [comment]
It is straight lines from my tests. it doesn't try to calculate a path. If there is something in between you and the second pos (ie tree stand) even if you could walk around it one tile and get there it will say the path is not clear.

**Comment by nwinter** [comment]
I want to make it return all hazards instead of just visible ones for performance, because then we don't have to check line of sight (which is slow).

**Comment by nwinter** [comment]
Implemented this a while ago.
