### ISSUE TITLE
Level Start - Problem with Help Arrow 

### ISSUE THREAD

**Issue by joklawitter** [codecombat/codecombat#2043]
Wanting to start the desert level 'Medical Attention' the helping arrow, indicating what to equip, doesn't work properly. Can't start the level.
![bug1](https://cloud.githubusercontent.com/assets/2663480/5602477/5fc0acdc-9350-11e4-86ad-98e6803b362a.PNG)
Scrolling down does not affect the arrow.
![bug2](https://cloud.githubusercontent.com/assets/2663480/5602476/5fc03c48-9350-11e4-8886-1500a4f6bff3.PNG)

Occured with Chrome 39.0.2171.95, Win7, playing/learning JavaScript, Captain Anya Weston.

**Comment by nemoyatpeace** [comment]
I had this issue as well.  If you scroll through the items, you will find one that is highlighted green.  You need to purchase that sensing stone, or a better one.  (I'd get a better one as within two levels you will be required to purchase the next step up anyway.)  If you can afford it, just buy the top one so you don't have to worry about it.

That said, I agree that this is a bug in the display, need to better highlight what is needed.  Maybe to put the required items that have not been purchased yet in a list just after the restricted list.  Would also be good to be clear that the required item can also be improved upon instead of just getting the simple one.

**Comment by joklawitter** [comment]
Had the problem some levels before too. There one item was marked green. Here only the Rough Sense Stone is marked but restricted. So yeah, some better Sense Stone should be the option, but this is not indicated here. ;)

By the way, accessing 'this.pos' is possible even without the Rough Sense Stone.

**Comment by nemoyatpeace** [comment]
Yes, I think technically you can access any of the attributes, you just don't get documentation on it until you have the item.

**Comment by nwinter** [comment]
How about now?

**Comment by joklawitter** [comment]
I bought a better Sense Stone, so I can't test it anymore. However, it is now indicated that the stone has to be equiped. Even though the arrow does not follow the scrolling. ;)

Thanks for the fast help! :)
