### ISSUE TITLE
Spells need to be coded

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2065]
I'm working on adding the different spell functionality, but for some of them I'll need some help with what they are supposed to do, and not sure I can code all of them, thought I'd make this issue to cover all of them.  I'll add my descriptions for them, let me know if they are right.

- [x] disintegrate
- [x] dispel
- [x] fireball
- [x] flame-armor
- [x] goldstorm
- [x] invisibility
- [x] lightning-bolt
- [x] summon-burl
- [x] summon-undead
- [x] swap
- [x] teleport
- [x] antigravity
- [x] chain-lightning
- [x] time-warp
- [x] summon-fangrider
- [x] ice-rink

**Comment by nwinter** [comment]
**goldstorm**: I was thinking the coins would be flung from the sky over a short period of time, maybe bouncing a bit. Coins don't currently have `Moves`, and I wouldn't want to add it for performance reasons, but we could manually update their trajectories. Or we could do something easier.

**invisibility**: Does it cancel current targeting like `targeting.Hides` does? (I haven't checked, maybe this already works.) The new WebGL graphics can't really do alpha transparency like before, but if we set an effect to make alpha 0.25 or 0.5 or something, then if we fix it, it'll start working, sort of.

**lightning-bolt**: I was actually thinking that this would be an infinite range, single-target lightning attack where you could call a bolt of lightning from the sky. It would be easier to get the graphics and coding working this way, anyway. We could do it the bouncing way, which would be cool, just not sure that we'll be able to easily visualize that.

**summon-burl**: It may be easier for me to do this one, since the logic for getting ThangTypes to spawn right is particularly tricky.

**summon-undead**: Currently there's only one level of this spell (Unholy Tome V), so I don't know if it needs to be configurable. We do have skeleton art now.

**teleport**: It would be too OP if you could teleport enemy units, but maybe you can teleport yourself or friendly units. It should fail to work if you teleport into a Thang with `collisionCategory` `"obstacle"`.

**antigravity**: This would presumably just toggle the Movement System gravity to go the other way for a little while, and we'd see what happened then. (Maybe it only does it for Thangs in a certain radius). Really not sure how this one is going to play, but should be hilarious if nothing else!

**Comment by popey456963** [comment]
**invisibility**: Would it be cool to have something that looked like the ghost from SCII for each champion?  It might take a bit of art work, but it would make it really cool.  [Image](http://us.battle.net/sc2/static/images/game/unit/screenshot/thumb/ghost-zerg-thumb.jpg) and [Image](https://feb33d8763de0c0f2e0a-dd07187202f57fa404a8f047da2bcff5.ssl.cf1.rackcdn.com/images/MEDcVHzblQgW.878x0.Z-Z96KYq.jpg).
**lightning-bolt**: If it were infinite range, it would make some interesting strategies and it would be easier to code, however would it be too good?
**swap**: Does this have a range?  Otherwise it could be amazingly over-powered.
**teleport**: What would happen if you teleported to a position that made the game far easier, or impossible to complete?  I think the range should be quite short.
**antigravity**: If this works well, it would be cool!  Not sure if it would need new animations for each character (people walking in the air would look somewhat weird)

**Comment by sotonin** [comment]
My 2 cents.

Teleport: I think this should not have any params, it should teleport just the caster a set distance in a *random* direction. This would be an "escape" type spell. Give you a little room to get away and do something.

**Comment by nwinter** [comment]
We don't want to have any unit-specific art for the spells, since that's a ton of work, so currently it has to either be 1) Marks above their heads, 2) Marks on the ground around them, 3) projectiles, 4) simple AoE effects like the animated circles we have, 5) particle effects (but only if someone wants to build a particle effect system).

So far we haven't assigned teleport to anything, so it could either be an ultra-power skill on a high-end special-purpose item, or it could have some negative downside (long casting time, random direction, and/or short range). Swap could be used as a more interesting form for escaping, perhaps, since you have to have another unit at that position. (A minion or pet?) It should have a range limitation, for sure.

**Comment by sotonin** [comment]
The only problem with swap being an escape is that it doesn't help a bit in a duel situation. Because you'd be swapping with the enemy you are dueling and the whole point is to get away from them, if they are in your face swapping with them will do you no good. :)

**Comment by popey456963** [comment]
Hm, I'm going to sit on the fence here.
On the one hand it would be cool to have an escape mechanism that dosen't kill someone on your team.
On the other hand it would be good that you had to sacrifice a unit to do it.

**Comment by nemoyatpeace** [comment]
So, I guess my Lightning Bolt description is really more of a Chain Lightning description.

I agree, **if** teleport is to a position, we have to be very careful that it doesn't teleport to spots that break levels (think teleport outside of Sarven-Brawl Arena).  Maybe it has to be line of sight?

Swap should always be callable, I wouldn't want it to only be cast on friendly units, unless it is connected to a pet, so you only have it if you also have a pet to swap with.  But I like the idea of being able to swap with any unit inside a given radius. Could be really fun if it also meant that enemy missiles would now hit the swapped unit.  i.e. you just shot an arrow at me, I swap places with you and your arrow hits yourself!  Not sure if this can be done.

**Comment by nemoyatpeace** [comment]
Looking at the spells yet to be coded, and knowing that casters are already pretty strong for survival, would be nice to see more aoe spells with higher damage on the higher end items.  I guess poison-cloud does that and timewarp would be an aoe debuff.

**Comment by nwinter** [comment]
Typically the wand / staff has the strong attack spell, with the spellbooks having some attack but more support / survival / fun stuff. Don't want too many attack spells to be able to stack, because the DPS would be hard to manage if you could swap between four different attack spells, since their main drawback is cooldown.

**Comment by popey456963** [comment]
You have a point, what about if we had a group cooldown?  On League of Legends, a character called Udyr has it so that each spell he casts puts all of his other spells on a short cooldown.

**Comment by nwinter** [comment]
Doesn't sound like that added complexity buys us too much, especially before we have the ability to visualize cooldowns (which we really need).
