### ISSUE TITLE
Detect and fix problems where required granted items show "undefined" item price

### ISSUE THREAD

**Issue by BloodJohn** [codecombat/codecombat#2140]
http://dl1.joxi.net/drive/0000/0890/13178/150125/f2a068e0b3.jpg

Old account, can't buy items in "forest" first mission

price: "undefined"

**Comment by popey456963** [comment]
You don't buy that book if I remember correctly, you get it for free after completing a mission.  http://discourse.codecombat.com/t/when-do-i-get-which-item-a-reference/2212 - Try completing forest level 2 (winding trail) again to get it.

**Comment by BloodJohn** [comment]
http://dl2.joxi.net/drive/0000/0890/13178/150125/b2feb27873.jpg

Thanks! After completed dungeon, i see first and last mission. But selected the last mission.

**Comment by popey456963** [comment]
This issue should be closed.

**Comment by nwinter** [comment]
In the case where the item has "undefined" price, we know that either:

1. There's a bug where the achievement isn't awarding the item properly, like in #2142;
2. The player has done the level before the achievements were set up properly, and recalculating achievements hasn't worked to award them the item (or hasn't been done yet);
3. The unlocks aren't configured properly; or
4. The player has skipped ahead to the level before unlocking it.

We should be able to detect and fix this client-side so that this kind of problem isn't a blocker for players.
