### ISSUE TITLE
Known Enemy level completed but no gems awarded & glasses not unlocked

### ISSUE THREAD

**Issue by rkt88edmo** [codecombat/codecombat#2142]
We completed the Known Enemy and it shows in our profile as complete and we saw the Victory screen at the end saying that the Crude Glasses were unlocked.  When we enter Master of Names it shows us as not having the Crude Glasses with the big yellow error pointing out that they are required in the inventory and we can't start the level.  I've reloaded the game and passed known enemy multiple times but the map does not show the victory flag planted on Known Enemy

My son is playing on a machine with IE 11.0.96....

**Comment by popey456963** [comment]
That's a very interesting error @rkt88edmo - Although we get lots of reports of items not being given for completing the level once, the trigger usually fires the second time they complete the level.  

When you complete the level, do you get any errors in console.  You can find out how to open the console in many browsers [here](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers).

**Comment by rkt88edmo** [comment]
Switched over to firefox on my machine, and it shows complete as expected.  We can mark closed for now and I will go back to the other machine and check what is going on in IE.  Thanks for the quick reply and link to how to open the console.  My first post of anything on github :)

**Comment by nwinter** [comment]
I'll keep this open until we can figure out what was going on in IE. Thanks for the bug report, @rkt88edmo!

**Comment by nwinter** [comment]
@differentmatt Seems like this is the same bug as what we originally fixed with the [cache: false](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/modal/HeroVictoryModal.coffee#L89-L89) line in HeroVictoryModal, but I still see the same behavior in IE: the achievements don't increment gems/exp (and presumably items) on the User object when going into the victory modal.

It works when the dev tools are open, because they disable caching. So I know it's a caching problem, and I was able to figure out that the rewards aren't being assigned (as opposed to the awards being assigned and then overwritten with a cached `me` object).

But how could this be? Didn't it start working after you fixed it with `cache: false`? Did something break it again in another way that invalidated the `cache: false` behavior?

**Comment by differentmatt** [comment]
Yes, the `cache: false` fixed the problem I investigated back in December.

I see the gems not being awarded in IE11 today.  I'll investigate.

**Comment by differentmatt** [comment]
Fixed by https://github.com/codecombat/codecombat/commit/6b9d8161ef16aa1153d952f3a60e9bd36ca81372
