### ISSUE TITLE
Flags do not appear on completed levels (IE11)

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2148]
In IE11 the flags that are supposed to appear to let you know which levels you have already completed are not appearing while connected over https.  This appears to be a mixed content issue.

**Comment by yaur** [comment]
This is happening because IE caches AJAX calls even though we put pragma: no-cache (this is arguablly correct behavior) https://github.com/yaur/codecombat/commit/13690cd8013f29a8f0222e31f7c9cd585c512afc prevents this

**Comment by nwinter** [comment]
I wonder if using `{cache: false}` instead of `null` [here in the LevelSessionsCollection fetch](https://github.com/codecombat/codecombat/blob/master/app/views/play/CampaignView.coffee#L54-L54) would also work. If so, then we probably need to make this sort of fix all across the site for IE support. We already noticed one bug with IE not reloading the User when beating the level to get rewards [here](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/modal/HeroVictoryModal.coffee#L88-L88), and adding `cache: false` saved the day there.

**Comment by yaur** [comment]
If you are using jquery for the ajax calls (haven't dug in enough to know yet) you can do something like `$.ajaxSetup({ cache: false });` to prevent this globally.  This is probably a better solution than fixing it on a case-by-case basis.

**Comment by differentmatt** [comment]
This problem seems to be fixed on IE11 Win7.  Please reopen with the OS version and a screenshot if you still see this.
