### ISSUE TITLE
I18NEditCampaignView can't save i18n due to lack of versioning

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2173]
@sderickson It looked like we were setting up the Campaigns to have i18n properties, so I finished making an [I18NEditCampaignView](https://github.com/codecombat/codecombat/blob/master/app/views/i18n/I18NEditCampaignView.coffee#L18-L18) and using the i18n from the model in 57d12c1, but there are two issues:

1. Diplomats can't save to the Campaign model. It dies [here](https://github.com/codecombat/codecombat/blob/master/server/commons/Handler.coffee#L363-L363). Is this something we can easily fix?

2. After we save it, adjacent campaigns won't update the i18n until they are deleted and re-added. I thought that we could do something simple [here](https://github.com/codecombat/codecombat/blob/master/app/views/editor/campaign/CampaignEditorView.coffee#L337-L337) to have it always refresh that data, so at least it'd be updated whenever the campaign was saved, but I'm not clear on how that update should work. Tips?

**Comment by sderickson** [comment]
@nwinter Fixed 1. Part 2, I'd recommend creating middleware on the Campaign server model to have it run a mongo update query. Since the adjacentCampaigns property is an object, you can do something like { 'adjacentCampaign.#{campaignID}': { $exists: true }} for a query to find all Campaigns that are linking to the one that changed, and something similar for an update object.
