### ISSUE TITLE
If a user does't have a submittedProgramingLanguage level loading stops

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2181]
[This replay](http://codecombat.com/play/level/criss-cross?team=humans&opponent=54885edf5c80aac606ad94d5) consistently results in the error:
"Uncaught Error: Specify a code language to create an Aether instance"
Per Nick this user doesn't have a submittedProgramingLanguage.
seems like this shouldn't be possible, but we should also probably not be simulating users in this state.

**Comment by sotonin** [comment]
Haven't encountered this one

**Comment by nwinter** [comment]
I've made it less likely that a user will be able to submit a match with no `submittedCodeLanguage`, and also I've set submittedCodeLanguages for the only 20 sessions of all time that were missing them (which is consistent with the hypothesis that the cause is the race condition that I just fixed). So let's keep our eye out, but hopefully that was it.
