### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#2254]
In first place, when I scroll through the leaderboard, it feels weird, because it hides behind the upper wood instead of the first one.

FROM
![1](https://cloud.githubusercontent.com/assets/6980488/6093624/c595e99a-aefe-11e4-9b0f-9f21fae38e23.png)

TO
![2](https://cloud.githubusercontent.com/assets/6980488/6093626/d140ad20-aefe-11e4-9b3b-5d7a90f51343.png)

Also, in the selection screen, the "Time" word could be separated from the word "Today".
![3](https://cloud.githubusercontent.com/assets/6980488/6093629/e3691f00-aefe-11e4-8e85-e0786c1ab441.png)

**Comment by nwinter** [comment]
The first part is a bug; there should be less margin or padding on that child view, and it should be positioned lower, so that it would get cut off right about where the paper ends.

Styles for that are [here](https://github.com/codecombat/codecombat/blob/master/app/styles/play/modal/leaderboard-tab-view.sass) and [here](https://github.com/codecombat/codecombat/blob/master/app/styles/play/modal/leaderboard-modal.sass).

Could you explain more about what you think would look better for the timespan / score category subtabs? I know the current design isn't very good, so some better design ideas would definitely help, but I'm not sure what you mean.

**Comment by divyanshu013** [comment]
@nwinter simply "Today" instead of "Time" and "Today" in the same tab could look better like in the other sub tabs. Please let me know what do you think. I'll take up this bug.

**Comment by nwinter** [comment]
Ah, but that wouldn't work well when there are two categories of scores, like when it can be "Time" and "Damage Taken".

**Comment by Imperadeiro98** [comment]
I mean, the "Time" string could be separated from the "Today", but I'm am the not the best person to talk about design.

**Comment by AnirudhGP** [comment]
Hi. This is my first bug here. Can i work on this?

**Comment by nwinter** [comment]
Ah, looks like @divyanshu013 beat you to it. There are plenty of older good-for-newbies bugs that need help, though!

**Comment by AnirudhGP** [comment]
Ok thanks anyways :)
