### ISSUE TITLE
Multiplayer Levels on Profile contains other levels

### ISSUE THREAD

**Issue by Vlevo** [codecombat/codecombat#2325]
There are several levels listed in my "Profile | Multiplayer Levels" that are neither multiplayer nor repeatable (while the repeatables aren't "multiplayer" per say, I can see those maybe belonging there) such as "The Raised Sword", "Seige of Stonehold", "Mad Maxer", etc.

**Comment by nwinter** [comment]
Right! The problem is that the `isMultiplayer` check is wrong, since we have teams defined for many sessions now: https://github.com/codecombat/codecombat/blob/master/app/models/LevelSession.coffee#L41-L41

Not exactly what it should be instead, but something better than just the `team` check. Maybe only when there is `submittedCode`? Won't show them up as multiplayer until the players submit at least once, but that's better than this.

I guess I'l just try that.

**Comment by Vlevo** [comment]
Those levels still appear in my "Profile | Multiplayer levels" list. :-(

**Comment by sotonin** [comment]
I'm still seeing a slew of single player ones listed under multiplayer as well. even on direct.

**Comment by Vlevo** [comment]
I don't know what qualifies as "submitted" code but, a lot of levels have a "submit" button.
Only "multiplayer" levels seem have a score. (of course this would also cut out the levels that one has never sucessfully submitted.)

**Comment by nwinter** [comment]
I have not deployed to production yet, no.

**Comment by Vlevo** [comment]
Am I right in assuming it just went live??
Since it now says:

Multiplayer Levels
No Multiplayer games played yet.

Which isn't true.

**Comment by nwinter** [comment]
Have you submitted the multiplayer games to the ladder? Which levels aren't showing up that should, and what's your username? I'll check it out.

**Comment by Vlevo** [comment]
Username is the same :)  Vlevo

Well, I guess I am only assuming that these are "multiplayer" since they are ladder games:

Cavern Survival
Multiplayer Treasure Grove
Dueling Grounds

(last matches were 3+hrs ago as of this post)

Are there any other on the map ladder games?
