### ISSUE TITLE
Select language, not ordered either ascending or descending

### ISSUE THREAD

**Issue by matifol** [codecombat/codecombat#2329]
How about ordering languages by ascending instead of this? It seems pretty random.

![screen shot 2015-02-16 at 20 14 42](https://cloud.githubusercontent.com/assets/7047431/6217859/a46acab2-b618-11e4-8e1b-63f41b1956e1.png)

**Comment by matifol** [comment]
Spelling error

**Comment by nwinter** [comment]
It's ordered to what I originally thought the popularity would be, based on some old analytics data from before we actually had any translations, plus keeping related languages together.

I could see going for alphabetization, but I could also see for just updating it to be in order of real CodeCombat popularity now. It's not very convenient for those languages lower on the list, and I wouldn't want to put Chinese (zh) or Russian (ru) all the way toward the bottom when we have so many players needing to choose those, especially since English locale code alphabetization isn't as easily grokked by some players using different character sets.

@Imperadeiro98 @nixel2007 @ArthurLu @mogsie @Martin005 what do you guys think about ordering by popularity versus ordering by alphabetical versus some other ordering?

**Comment by Martin005** [comment]
I think that it would be important to have languages ordered by popularity. E.g. if some Russian (as mentioned) goes to your site and have to sroll all the way down for selecting his language, he is not going to be much happy about that.

**Comment by Imperadeiro98** [comment]
I agree with @Martin005! It would be nice if it was ordered according to CodeCombat popularity, plus everyone could see if they have many people playing from their country.

**Comment by matifol** [comment]
Solid points here guys. Just throwing out ideas tho; how about a pre-selected top of, let's say top 5, and then alphabetical, divided by `---------------` or something. As a player from a country with not that many players, I might get the idea that my language is not present. Have used this approach previously with pretty good feedback from users.

    English (by populatiry)
    Chinese
    Russian
    -----------
    Albanian (alphabetical)
    Latvian
    Norwegian
    Swedish

All this considering a smaller number of very popular languages.

**Comment by mogsie** [comment]
:+1: for @matifol's suggestion about having the top 5 languages at the top, and then the rest.  I also find the non-alphabetical (seemingly random) order to be quite odd! :)

**Comment by Martin005** [comment]
Yea, I think the @matifol suggestion for top 5 used languages and other ordered alphabetically.

**Comment by nixel2007** [comment]
Just wanted to offer variant as @matifol did. And I think the "5" number for number of languages is just what we need.

**Comment by Imperadeiro98** [comment]
It seems like we all agree :)

**Comment by nwinter** [comment]
Here are the language popularities for registered users:

```
74.20%	en-US
5.04%	zh-HANS
4.77%	ru
3.98%	es-ES
2.91%	fr
1.11%	en-GB
0.90%	pt-PT
0.84%	es-419
0.74%	ja
0.69%	de-DE
0.65%	pl
0.61%	zh-HANT
0.41%	nl-NL
0.29%	it
0.28%	ko
0.21%	hu
0.19%	th
0.18%	sv
0.18%	tr
0.18%	pt-BR
0.17%	uk
0.14%	da
0.14%	ro
0.13%	cs
0.10%	en-AU
0.10%	id
0.10%	vi
0.09%	bg
0.09%	ar
0.09%	nb
0.09%	fi
0.07%	sk
0.07%	el
0.06%	he
0.04%	lt
0.03%	ca
0.03%	sl
0.03%	de-AT
0.02%	nl-BE
0.01%	sr
0.01%	nl
0.01%	fa
0.01%	es
0.00%	de-CH
0.00%	ms
0.00%	hi
0.00%	zh-WUU-HANS
0.00%	pt
0.00%	nn
0.00%	zh-WUU-HANT
0.00%	de
0.00%	gl
0.00%	ms-BA
0.00%	ur
0.00%	mk-MK
```

Following (with difficulty) a similar alphabetization scheme to what Wikipedia's language sidebar uses, and keeping similar language groups together, then gives us 93.56% coverage with the top five language families (which is actually 8 choices):

```
English (US)
English (UK)
简体中文
繁体中文
русский
español (ES)
español (América Latina)
français
------------------------
العربية
български език
Català
Čeština
Dansk
Deutsch (Deutschland)
Deutsch (Schweiz)
Deutsch (Österreich)
Ελληνικά
فارسی
Galego
한국어
Bahasa Indonesia
Italiano
עברית
Język polski
Lietuvių kalba
Limba română
Magyar
Македонски
मानक हिन्दी
Bahasa Melayu
Nederlands (België)
Nederlands (Nederland)
日本語
Norsk bokmål
Norsk nynorsk
Português (Portugal)
Português Do Brasil
Српски
Slovenčina
Slovenščina
Suomi
Svenska
ไทย
Tiếng Việt
Türkçe
Українська Мова
اُردُو
吴语
吳語
```

We can probably delete English (AU), especially since we do very little localization for flavors of English. The biggest loser would be pt-PT, which is the 7th-most-popular individual language, but which would be down in spot #36. But overall, it's much better. Cool?

**Comment by matifol** [comment]
Yea, looks great.

**Comment by nixel2007** [comment]
Hm... Alphabetical list looks strange a little, but if it like wiki does, it's OK. 
Also we could change one list of languages to 3-4 lists, like translate.google.com does - it can resolve the scroll-scroll-scroll problem.
