### ISSUE TITLE
Repeatable levels needs a visual indicator in campaign view

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2390]

**Comment by nwinter** [comment]
Let's try using the particle system to keep showing something around them even when they are unlocked. We would adjust [this logic](https://github.com/codecombat/codecombat/blob/master/app/views/play/CampaignView.coffee#L331-L338).

By the way, the particle system is only enabled in Chrome right now, because it seemed to cause problems in all the other browsers in our A/B tests even after handling all the errors we knew about from WebGL support problems.

**Comment by differentmatt** [comment]
We should show the current level you're on as well.  E.g. if I'm on level 5, there might be a little 5 on the flag in the world view.
