### ISSUE TITLE
Multiplayer levels need a visual indicator in the campaign view

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2391]

**Comment by nwinter** [comment]
Let's try using the particle system to keep showing something around them even when they are unlocked. We would adjust [this logic](https://github.com/codecombat/codecombat/blob/master/app/views/play/CampaignView.coffee#L331-L338).

By the way, the particle system is only enabled in Chrome right now, because it seemed to cause problems in all the other browsers in our A/B tests even after handling all the errors we knew about from WebGL support problems.
