### ISSUE TITLE
The Agrippa Defense rvalue

### ISSUE THREAD

**Issue by thejakeprime** [codecombat/codecombat#2481]
![image](https://cloud.githubusercontent.com/assets/7458272/6542304/13518196-c4ba-11e4-8d0e-76cfa802e39e.png)
This is the error I get in this Python mission. The help button doesn't speak to this cryptic error.

**Comment by Vlevo** [comment]
AND, the error is actually on the previous line.

Assigning to rvalue means you are assigning to something that should be on the right side of an assignment not the left side . . . huh!?  Yup, I agree...

For example: "x+1 = y+2", the "x+1" belongs on the right side of an '='. . it's an r(ight)value. "z= x+1"

In your code, on the line before (which is where the error is a lot of times.) you have '=' when you should have '=='. It thinks you are trying to assign "True" to "self.isReady(cleave)" instead of checking to see if they are equal.
