### ISSUE TITLE
Text-fit bug - /play - heroes

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2501]
Similar to #2497:

![char_screen_ru_100](https://cloud.githubusercontent.com/assets/99704/6589123/7ae0caf6-c758-11e4-80b1-04c070c6ffd2.png)

Blue stat bar is cut off on the bottom. And we haven't even translated Naria's description yet.

**Comment by laituan245** [comment]
Probably this issue should be re-opened because someone has just added the Russian translation for Naria's description and the blue stat bar now is cut off on the bottom again.

![screenshot from 2015-03-12 13 45 45](https://cloud.githubusercontent.com/assets/3805149/6612483/5b0d5348-c8c0-11e4-9fae-0da265726099.png)

**Comment by nixel2007** [comment]
haha, it was me. :D
i'll try do something.

**Comment by nixel2007** [comment]
Done.
![default](https://cloud.githubusercontent.com/assets/1132840/6626579/ed438de8-c908-11e4-9e85-4ca8d7f64e85.PNG)

**Comment by nixel2007** [comment]
Can be closed.
