### ISSUE TITLE
Alert user when they try to sponsor their own subscription

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2542]
It needs to be clearer that you shouldn't subscribe yourself via the Managed Subscriptions section here:
http://codecombat.com/account/subscription

If someone does try this, we need to direct them to the first subscribe button at the top of the page.

Code is here: https://github.com/codecombat/codecombat/blob/master/app/views/account/SubscriptionView.coffee

**Comment by sirui-sun** [comment]
I interpret the above as: if the user enters only their e-mail address in the Managed Subscription e-mail box, direct them to the personal subscribe experience (otherwise reachable through the first subscribe button at the top of the page). Is that right?

What would be the expected behavior if the user enters other e-mail addresses in addition to their own in the Managed Subscription e-mail box?

**Comment by differentmatt** [comment]
We should notify the user if any of the email addresses they enter is their own.  It's more likely that they will include themselves in a list of email addresses to subscribe.

An easy way to notify the user would be a simple popup or dialog that says something like 'Please use the Personal Subscription' button above to subscribe yourself.'

Trying to subscription yourself via the Managed Subscription method is currently blocked on the server side: https://github.com/codecombat/codecombat/blob/master/server/payments/subscription_handler.coffee#L446

**Comment by differentmatt** [comment]
We also display the wrong price when someone tries to subscribe themselves.  E.g. subscribing yourself and a friend shows $17.98 in the Stripe dialog, but only charges $9.99.

**Comment by nwinter** [comment]
Sponsored subscriptions deprecated now, so we don't need to build this.
