### ISSUE TITLE
Functions do not seem to work in Lua

### ISSUE THREAD

**Issue by shakesoda** [codecombat/codecombat#2635]
I tried a few different things when building my zero-sum entry and this ended up totally ruining my plans.

```lua
local function whatever()
    self:foo()
end

whatever() -- nothing happens, not even an error.
```

the behavior is the same for anonymous functions and functions stored in tables, too.

Here's my entry trimmed to just item pickup, for demonstration:
```lua
loop
	local ideas = {} -- hang onto all possible actions for prioritization
	
	-- work out best nearby item to pick up, save it into ideas
	do
		local items = self:findItems()
		local bias = -5 -- bias away from most valuable, helps to avoid enemy.
		local nearest = self:findNearest(items)
		local best_nearby_item = nearest
		for _, item in pairs(items) do
			if item.value + bias > best_nearby_item.value and
			   self:distanceTo(item) + bias < self:distanceTo(nearest) and
			   self:isPathClear(self.pos, item.pos) then
				best_nearby_item = item
			end
		end

		if best_nearby_item then
			-- cc doesn't have table.insert
			ideas[#ideas+1] = {
				name = "get_item",
				importance = 1,
				action = function(self)
					self:move(best_nearby_item.pos)
				end
			}
		end
	end

	table.sort(ideas, function(a, b)
		return a.importance > b.importance
	end)

	-- do whatever is the most important (in order of priority)
	-- note: there's not enough info about how actions get executed by code
	-- combat... it'd be really nice to have better docs.
	for _, ideas in ipairs(ideas) do
		ideas.action(self)
	end
end
```

I had various mysterious issues when putting together my entry, too, some things I had to work around with pcall and some errors that just vanished when I rearranged stuff in a functionally identical way.

**Comment by nwinter** [comment]
@basicer know what's up with this?

**Comment by basicer** [comment]
Firsly, thanks for really kicking the tires in on lua!

This isn't actually a problem with lua specifically (though you will see it more often) but a problem in all languages in code combat.  What happens is this:

When code combat compiles your code to be run, it has to make a lot of changes to it to support "blocking functions".  What is going in is Aether is trying to do a bunch of hackery to basically make something like `coroutine.create()` work in javascript.  It does this by detecting what functions could possibly call a blocking function and rewrites those functions as generators.  "Could possibly call a blocking function" is defined as contains any call expression.  Aether keeps track of the functions it has rewritten into generators, and when it comes across the call-site of such a converted function, replaces the call with a call that will also enumerate the generator.  This usually works, but if you pass the function (that has now been rewritten as a generator) by reference into a function, inside that function we don't know it's been rewritten.  Because of this, we don't rewrite the call, and calling the generator just returns to us an iterable, resulting in the function not really running.

**Comment by basicer** [comment]
Here's an example in javascript that would have the same problem.

```
function double(a) { return a*a; }
function double2(a) { return double(a,b); }
this.say([8,6,7,5,3,0,9].map(double).join(","));
this.say([8,6,7,5,3,0,9].map(double2).join(","));
```

It will say `[object Object],[object Object],[object Object],[object Object]...` the second time, because the return value of `double2` is going to be a generator, not the real return value.  `double` works because it contains no call expressions, so it is not converted to a generator.

**Comment by shakesoda** [comment]
This is still an issue for Ace of Coders, here's some more test cases: https://gist.github.com/shakesoda/80b69243b98018510c9e

(at least this time I'm not late to the party, so I can work around it...)

**Comment by MisterInSayne** [comment]
I found out that local function doesn't work, yet function does in lua.

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter.
