### ISSUE TITLE
electrocute on non electrocutable unit

### ISSUE THREAD

**Issue by grossjonas** [codecombat/codecombat#2648]
Is there any way to check if an enemy is electrocutable other than checking all possible `enemy.type`s?

For example:
In [keeping-time](http://codecombat.com/play/level/keeping-time) there is a `palisade` which is non electrocutable. Trying to electrocute it will throw an error and stale the hero.
So you have to do something like `this.isReady('electrocute') && (enemy.type === 'ogre' || enemy.type === 'scout' || ...)`.
It would be nice to have an item which gives you something like `this.isElectrocutable(enemy)`.

For back reference:  [discourse entry](http://discourse.codecombat.com/t/how-to-check-if-enemy-is-electrocutable/3445)

**Comment by Zerrien** [comment]
Electrocute delivers an 'effect' on the target. Palisades don't have the 'effects' component, so that's the problem.

But, as for an actual solution...
* Grant the player access to a "this.canEffect('enemy', 'electrocute')" type function. [Complicated...]
* Fail silently, consume the cast, and let the user continue on after failing to apply electrocutes. [Unintuitive...]

If there is an obvious, good solution I'm missing, please share!

**Comment by Vlevo** [comment]
Casting what is essentially slow on an immobile object would very intuitively do nothing...(Why your hero would do something that dumb is, of course, a different story. Seems like doing nothing, consuming nothing (time or "use") would be better, except, of course, that this would lead to your hero continually, "not doing it.")

Seems like "canCast" already contains all the functionality to do what we would want, so it shouldn't be that "complicated." Which item should give this ability: "canElectrocute(target)" . . . the ring itself of course.

I am working on the patches for this. Hopefully, it won't take too long...

**Comment by grossjonas** [comment]
\o/ thank you!
