### ISSUE TITLE
Leaderboard button 

### ISSUE THREAD

**Issue by dheerajdake** [codecombat/codecombat#2659]
There should be a leaderboard button as soon as we click Play, before entering the levels. It will be better if placed beside the achievements.

**Comment by nwinter** [comment]
We try to avoid doing things that will slow the player down on the task to playing the next level–I think this would fall into that category. Additionally, since the leaderboards contain links to view the solutions, I don't want to show the leaderboards until the player has already done it herself. (Well, I guess we could add some logic to not show replay links until the player had done it.)

Why do we need a leaderboard button before the player has beaten the level?
