### ISSUE TITLE
Permit longer code execution between "heartbeats"

### ISSUE THREAD

**Issue by coder0xff** [codecombat/codecombat#2704]
I've been working on some algorithms that do preprocessing at the start of a round, and they're rather computationally intensive. I'm thinking of some possible ways the "infinite loop" detection could permit more expensive code. Currently, I'm doing `self.moveXY(self.pos.x, self.pos.y)` periodically, as a heartbeat of sorts, because it causes the smallest increment in game time AFAIK.
- The option to continue evaluation for another timeout period
- An option to extend the timeout period by a user specified amount/multiplier
- Programmatically get the number of cycles until a heartbeat needs to occur.
- Automatically advance the game time after a certain number of cycles occurs, like an automatic heartbeat. This would need a way to stop simulation (and not just playback).
- Multiplayer simulations permit a much higher threshold (or maybe it already does?)

**Comment by nwinter** [comment]
Hmm. The timeout is already 7.5 seconds. Is it really going to be fun to play if your code is taking significantly longer than that? Runtimes will expand to fill whatever limits we put, but I don't know if it'll actually make for a better gameplay experience.

What kind of preprocessing are you working on?

**Comment by coder0xff** [comment]
I'm using self.pathClear to do a bucket fill of the reachable map area, and
then doing another pass to relax the boundary. I'm planning to use the data
for risk avoidance. It's actually not that much work, but... my laptop
performance etc etc... I never get real time simulation anyway.

If you're interested, I can share the code. Maybe you can tell me if I'm
expecting too much.

**Comment by coder0xff** [comment]
I was wondering if one of the nicer sense rings offers map data.

**Comment by nwinter** [comment]
Sure, share the code–pastebin? Interesting approach.

We could make some obstacle data available on high-end sense-stones. What kind of methods/properties do you think would make sense?

**Comment by coder0xff** [comment]
http://pastebin.com/Qtf7nvfP

**Comment by nwinter** [comment]
Ah, I see. Yeah, that's just running very slowly (even though it doesn't end up being too-too many statements; presumably whatever the transpiler is doing to it is making parts of it very expensive).

I'm guessing that even if we made this work better in terms of yielding CPU and not triggering the infinite loop detector, it still wouldn't get us up to, say, 5x better before you also started seeing too many out-of-memory crashes and just horribly slow performance. And it's pretty complicated to do, when most of the time we should probably be making the timeout shorter to rescue our less-advanced players from infinite loops.

I did have a way to do most of what you suggested when we were doing chooseAction methods instead of plan methods, where we didn't have to do the automatic yielding, but that wouldn't be easy to port over to our generator-based approach.

Do you think you'd have a much easier time getting this to run performantly if a sense-stone gave you a 1-meter-resolution grid which told you where all the obstacles were?

**Comment by coder0xff** [comment]
That would be optimal. This is pretty much a hack to do just that.

Though, I'm sure I'll come up with other ways to have massive code. 8D

**Comment by nwinter** [comment]
I wonder if this code is running any faster in the new interpreter?
