### ISSUE TITLE
The Geometry of Flowers - With only one ring

### ISSUE THREAD

**Issue by ChristianKleineidam** [codecombat/codecombat#2740]
It seems like it's impossible to play The Geometry of Flowers without having brought a separate ring.
Both ring slots need to be filled to play the level and that doesn't make sense.

**Comment by Vlevo** [comment]
I would guess that the issue is that the requirement for the level is "right-ring" ring of flowers, but if you have no rings the ring of flowers defaults to filling the LEFT-ring slot (the ring of speed defaults to the right-slot.) I believe this is because the slot order in the rings components is right,left for the ring of speed and left,right for the ring of flowers . . . so either the hand-ring requirement needs to switch or the order on the ring of flowers needs to switch...???...
@nwinter which is preferable?
I have submitted a patch to the ring of flowers switching it to "right,left".
Every time I tried to test it, something seems to override the change I have made, I even tried changing what the ring does to no avail...???...

**Comment by Painted-Fox** [comment]
I'm also experiencing this issue.

![codecombat-about_to_equip_ring](https://cloud.githubusercontent.com/assets/1155602/7706402/3e9b7a9a-fe18-11e4-888b-84109c15cbbd.png)

![codecombat-ring_equiped](https://cloud.githubusercontent.com/assets/1155602/7706407/42cc03fa-fe18-11e4-9478-b622a10c2f69.png)

@Vlevo I think it shouldn't matter which slot the flowers need to be on.  It should only matter that the required ring is equipped.

**Comment by Vlevo** [comment]
@Painted-Fox What you think or what I think doesn't necessarily matter.

What matters is how it has been coded.

**Comment by Painted-Fox** [comment]
@Vlevo Can you point me to your patch, please?  Or point me to where these checks are being made? I'm curious to see the code.

**Comment by Vlevo** [comment]
For my patch I went the easy route and changed the item in the game (a database change). Unfortunately this didn't work. I don't know where in the code that runs the game this check is made (or I wouldn't have needed to make my "betting" comment I'd have looked.) :frowning:

(I assume that would be here in this repository somewhere...)

**Comment by UltCombo** [comment]
There's one more problem with the required items logic regarding rings here: you can equip any two rings and the "Play" button will be enabled, not requiring you to necessarily equip the Ring of flowers.

Looks like the "unequipped due to restrictions" logic referenced [here](https://github.com/codecombat/codecombat/blob/0df6da7efa3df9ff6cd0e65133ff31923a9a0ee8/app/views/play/menu/InventoryModal.coffee#L436) is not kicking in for rings.

**Comment by Vlevo** [comment]
It is actually worse than that...
![image](https://cloud.githubusercontent.com/assets/11031492/8394760/b61ae802-1d04-11e5-9c6e-28820440c261.png)

**Comment by UltCombo** [comment]
I'm taking a look at the [inventory modal code](https://github.com/codecombat/codecombat/blob/0df6da7efa3df9ff6cd0e65133ff31923a9a0ee8/app/views/play/menu/InventoryModal.coffee), it looks like the current logic regarding required items will accept any item in the slot which is not a restricted (blacklisted) item.

I can see the reason behind this logic choice, this makes it easy to accept a "better" item in that slot, as you just have to not blacklist better items instead of whitelisting all the valid ones -- e.g. the Kithgard Gates level requires the `tarnished-bronze-breastplate` but it allows you to use any other "better" armor as there's no restricted/blacklisted armor items.

Without major changes to the code, an idea would be to blacklist all rings except the Ring of flowers in levels which require the Ring of flowers (similarly to how all swords are blacklisted in levels which require a hammer).
This doesn't seem like a good idea though, seeing as if all the other rings are blacklisted then you wouldn't be able to equip them in the other ring slot.

**Comment by UltCombo** [comment]
Perhaps a better approach would be:

- When there's a required item for a given slot, whitelist all valid items for that slot in the [`requiredGear` items array for the given slot](https://github.com/codecombat/codecombat/blob/0df6da7efa3df9ff6cd0e65133ff31923a9a0ee8/app/views/play/menu/InventoryModal.coffee#L433), thus requiring one of the whitelisted items to be equipped in the given slot.

- Remove the "[accept any equipped item as long as it is not restricted](https://github.com/codecombat/codecombat/blob/0df6da7efa3df9ff6cd0e65133ff31923a9a0ee8/app/views/play/menu/InventoryModal.coffee#L436 (blacklisted))" behavior.

- Similarly to the point above, patch up the `requiredToPurchase` logic removing the "[equipped item is not in `allRestrictedGear`](https://github.com/codecombat/codecombat/blob/0df6da7efa3df9ff6cd0e65133ff31923a9a0ee8/app/views/play/menu/InventoryModal.coffee#L107)" bypass.

The plan above should definitely fix the ring issues (together with #2868 which allows required rings to be equipped on either ring slot).

However, it may also add a lot of burden when adding new items, as they might have to be added to a bunch of whitelists -- I'm not sure how much of a problem it currently is with the blacklists approach.

Hence I'd like to get some feedback on whether this sounds like a viable plan before spending too much time into it.
I wonder whether there is a better way around this? Perhaps special-casing the rings would be better, as the current logic seems to work decently well for the other item types.

**Comment by nwinter** [comment]
I don't want to whitelist items, because there are so many items to whitelist and it'll inevitably be someone's badass sword that we just added and they just bought and they can't use, which is not a good feeling for the player. Special-casing the ring slot here seems to be a better idea; we could even do something hacky and special case the Ring of Flower itself, since so far we haven't had to ever require any other rings.

**Comment by UltCombo** [comment]
@nwinter makes sense. I'll think of something if I have some spare time tonight.
Meanwhile, feel free to comment if anyone has suggestions.
