### ISSUE TITLE
Cavern survival doors should be clickable

### ISSUE THREAD

**Issue by ChristianKleineidam** [codecombat/codecombat#2742]
At the moment in the level [cavern survival](http://codecombat.com/play/level/cavern-survival) it's impossible to select doors by clicking on a door. Giving that attacking doors is part of what the level about, it would be useful if the user can click the doors to be able to see their name and their health.

**Comment by Vlevo** [comment]
While I don't necessarily disagree with the idea of being able to click the doors . . . attacking them isn't what the level is about, <b>surviving longer than the other hero</b> is, and cutting your way through to the other hero may not help with that.
(If you must attack them, doing so when they are nearest enemy might be healthier than just ignoring other mobs to preferentially attack the (eastern & western) doors. Most doors have the type "door". (I say most because there may still be some old ones that haven't been updated.))

**Comment by ChristianKleineidam** [comment]
I created a patch (but it's not yet accepted)

**Comment by nwinter** [comment]
Got it, thanks! Should show up sometime in the next day.
