### ISSUE TITLE
Reindeers in hunters-and-prey don't have a type

### ISSUE THREAD

**Issue by ChristianKleineidam** [codecombat/codecombat#2743]
At the start of hunters-and-prey I run:

    for friend in self.findFriends():
        self.say(friend)
        self.say(friend.type)

This works correctly for the archers but produces an error after saying the name `Reindeer 1`.

Furthermore it would be good if the reindeers would be clickable to allow even either access to their names and type.

**Comment by Vlevo** [comment]
You should really combine those say statements as they each waste time, even if just testing you need to get everything said before you get splatted, and you can't do anything while "say"ing (no unit commands, ...) to separate items in your say statement use: +" "+
(iow: friend.id +" "+ friend.type)

What are you trying to do with/to the deer? you can't command them...

Should they have type animal? and the pigs, cows, horses also? maybe livestock?

Currently they can be identified and/or ignored by "if/if not", "friend.type" (doing separate things for those with/without types.)

Also they are all named, "Reindeer" (Reindeer, Reindeer 1,  Reindeer 2, etc) so can be idnetified that way.

**Comment by ChristianKleineidam** [comment]
The code doesn't do the same thing when you combine the say statements given that  `self.say(friend.type)` throws an error when called on a reindeers. Separating the statements makes it easier to track down the location of the error. 

The soldiers are supposed to defend the reindeers. From that perspective it makes sense to order them to do defend them. That means I have to be able to select reindeers. 

Apart from that the `findByType` function is very handy for identifying units and it needs a type and doesn't work via the name.

Sand yaks are animals and they already have the type `sand-yak`. Given some animals the type `animal` and others a more specific type seems inconsistent.

**Comment by Vlevo** [comment]
There is a big difference between Reindeer and Sand-Yaks . . . reindeer are scenery and sand-yaks are units. In most levels reindeer/pigs/cows/etc are just scenery. Maybe since they aren't just scenery in this level they should have been given a higher status but, you are trying to do MUCH more than is really necessary to complete this level, obviously none of those things are needed to complete the level. OK, since I wanted to fix a separate bug, I went ahead and submitted a patch for your items as well (fixes hidden-sliding reindeer, type = reindeer and selectable)
