### ISSUE TITLE
Cloudrip Treasure - incorrect initial gold value causes infinite loop

### ISSUE THREAD

**Issue by dzhang314** [codecombat/codecombat#2767]
The following code appears to behave incorrectly on Cloudrip Treasure (optional challenge level in mountains):
```python
loop:
    if self.gold >= self.costOf("soldier"):
        self.say(self.gold)
        self.summon("soldier")
    self.say("Hey!")
    self.say("This part never executes!")
```
As you might have guessed, `self.say("This part never executes!")` is never executed. The problem appears to be that before the first frame, `self.gold` is set to `60`, but somewhere in between executing `self.say(self.gold)` and `self.summon("soldier")`, `self.gold` is set to `4`.

![2015-05-17 10_58_18-codecombat - learn how to code by playing a game](https://cloud.githubusercontent.com/assets/4504054/7671097/ac8d3de0-fc83-11e4-9383-3d55d11922c3.png)

This causes execution of `self.summon("soldier")` to continue infinitely, preventing further action from occurring. The player character appears to repeatedly target random locations in a several meter radius as it executes.

**Comment by Vlevo** [comment]
This is a known problem.
Actually, the problem is the other way around.
The level is supposed to set you to zero, so that all summons are from peasant collection, and not from boss-star gold. but the boss star keeps winning the race to zero and for a split second you think you have 60 gold. if you place a wait(0.00001) (any sufficiently small number will do, since it can only wait for a minimum time.) then you will not experience the infinite attempt to summon, when you don't really have the money to summon.

**Comment by nwinter** [comment]
@Catsync I just added an `ignoreItemGold` property to the Inventory System. We can set this on a bunch of levels where we had previously banned boss stars and instead allow them, since they won't affect gold collected goals or leaderboards when it's set. Can you put on your list to update that setting on Siege, Treasure, etc. levels and allow the stars?
