### ISSUE TITLE
Clojure can't (.say) numbers

### ISSUE THREAD

**Issue by J-F-B-M** [codecombat/codecombat#3044]
http://discourse.codecombat.com/t/is-kithgaard-mastery-possible-to-complete-in-the-clojure-language-without-the-ability-to-cast-to-strings/4976/4?u=j_f_b_m

This is an issue migrated from the forum.

A user reported that he cannot say numbers (as they are no strings) in the experimental language Clojure. The solution would usually be to cast them with (str <number>), but that method is not available (unknown if at all or only in the dungeon).

**Comment by tchalvak** [comment]
Yeah, that's the situation.

**Comment by Driphter** [comment]
``` Clojure
(.say this 1)
```

``` Clojure
(def gems 1)
(.say this gems)
```

Both of these seem to be working as intended. Perhaps the user misunderstood the level goals?

**Comment by tchalvak** [comment]
![image](https://cloud.githubusercontent.com/assets/23353/10062675/35376980-6233-11e5-816c-7132c2d60ac4.jpg)
Fails on exactly such a line.

Full code from the forum thread:

    ;; Count how many gems you pick up, and then say the current count when near a fireball trap to disable it.
    ;; The raven at the start will give you a password. Say the password near a door to open it.
    ;; Kill ogres when you get near them.
    ;; You can use a loop to repeat all of the instructions as needed.
    ;; If you beat this level, you can skip to the Forest World!
    (if (not gems) (def gems 0))
    (.moveRight this)
    (dotimes [n 2] (.moveUp this))
    (dotimes [n 2] (def enemy (.findNearestEnemy this)) (if enemy (.attack this enemy)))
    (.moveLeft this)
    (dotimes [n 2] (.moveUp this))
    (dotimes [n 2] (.moveRight this))
    (.moveUp this)
    (inc gems)
    (.moveDown this)
    (.moveRight this)
    (dotimes [n 2] (.moveDown this))
    (.say this gems)

**Comment by Driphter** [comment]
It's undefined due to your `if` form at the top. You're using the `gems` symbol before it's ever bound. This is causing a reference error. You can see the error more clearly here:

``` Clojure
(if (not gems) (.say this "test"))
; Results in "Line 1: ReferenceError: gems is not defined"
```
Unlike in Javascript, you can't use a symbol before it's bound. Here's your `if` form in a Clojure REPL:

``` Clojure
=> (if (not gems) (def gems 0))
=> clojure.core/eval  core.clj: 2927
   ...
             java.lang.RuntimeException: Unable to resolve symbol: gems in this context
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: gems in this context
```

For some reason though, the interpreter is handling this case in an odd way. I'm assuming that it sees that the `(def gems 0)` is in there somewhere so it doesn't throw a ReferenceError. Instead it seems that the form using the unbound symbol returns `null` or `undefined`:

``` Clojure
(if (not gems)
    (def gems 0)
    (def gems 1))
(.say this gems)
; Says "1"

(if gems
    (def gems 0)
    (def gems 1))
(.say this gems)
; Says "1"

(if (+ 1 gems)
    (def gems 0)
    (def gems 1))
(.say this gems)
; Says "1"
```

Luckily though, all of this can be avoided by simply using `(def gems 0)` without the `if` form to begin with. Which makes me wonder why you had the `if` form there to begin with. In the future, I'd try to avoid using `def` anywhere inside of another form. I've never seen a reason to put `def` inside of a form, at least. If you find that you want to, the better solution would probably be using `let` or `set!`.

**Comment by tchalvak** [comment]
If I recall, I was prepping for the need to create multiple loops after this first one in that board.  In this case, my imperative coding practices have tripped me up!  I totally thought I had found an omission in the "gaining of language functions" for the experimental clojure playthrough.  But nope.  I'll try a few alternate approaches when I run across a weird situation like this, in the future.

Issue can totally be closed, thank you!
