### ISSUE TITLE
self.summon("arrow-tower") creates an arrow tower waiting for commands (doesn't attack)

### ISSUE THREAD

**Issue by taerilan** [codecombat/codecombat#3147]
![arrow-tower](https://cloud.githubusercontent.com/assets/15383948/10826468/3deb3ebe-7e6a-11e5-89c6-6435127b0e12.png)
With comand:

self.summon("arrow-tower")

in level "Cloudrip Siege" was able to summon arrow tower, but tower wouldnt attack, after being unable to figure out how to comand tower, have tried instead to use comand:

self.build("arrow-tower")

comand, which worked and tower was attacking.

Reporting here as i fell that being able to use:

self.summon("arrow-tower")

comand to summon tower is bug in game, since tower doesnt atacks there afterwards. Of course I might be wrong, hope I helped a little.

In screen shot, I hope you will be able more clearly to see what I am saying, you can see enemies attacking towers, but they are all on full health, becasue towers arent attacking back. Tried to use comand to make towers attack, but coudnt do it.

Thank

**Comment by nwinter** [comment]
Hmm, right–anything created with `summon` will wait for you to command it instead of doing anything on its own, and anything created with `buildXY` will start auto-attacking until you command it once, but behind the scenes, the unit list for `summon` and `buildXY` is the same. Not sure the best thing to do here, but maybe the next step is to make it so that things that you `summon` but couldn't command don't have their `commander` property set (and so thus act like they were built with `buildXY` and actually do the attacking). The code for that is in the `building.Builds` Component if anyone wants to tweak that and test it.

**Comment by binary-idiot** [comment]
I found the code in question, in the `existence.Builds` component. Is there already an existing list of commandable things that can be checked against?

**Comment by nwinter** [comment]
Commandable Thangs depend on what the Boss Star (or other item, but usually Boss Star) has in its `commandableTypes` configuration. You can see what Boss Star V covers here: http://direct.codecombat.com/editor/thang/boss-star-v

So by extension, you can check the player's `commandableTypes` to see what is commandable at runtime.

**Comment by nemoyatpeace** [comment]
I just fixed this one.
