### ISSUE TITLE
German Lua "Burls Beets Booleans" in English and a possible wrong info

### ISSUE THREAD

**Issue by headspeak** [codecombat/codecombat#3163]
In the German version the help comments are in English.
The help comment 
--self.say(False)
is not Lua. It should be 
--self:say("False")

**Comment by ikeban** [comment]
Hi headspeak,
I cannot help with German version - this is work for Diplomat.
If you can translate it (if you know English very well and want to help), here is link for level: 
http://codecombat.com/i18n/level/burls-beets-booleans (after it is loaded, just select German Language from drop down list at the top of the site)

I think that first you should get familiar with these sites:
http://codecombat.com/contribute/diplomat
https://github.com/codecombat/codecombat/wiki/Diplomat-Home

I will fix this level from LUA point of view probably tommorow (my deadline is end of this week). 
<b>I just want to post, that I work on this issue from LUA point of view- please leave this simply task </b> (I learn how to work with CodeCombat) <b>for noob like me</b> :)

**Comment by ikeban** [comment]
Hi headspeak,

I fixed it, and my patch is now in pending state.
If you want to see it, please select "Patches" tab from this link: http://codecombat.com/editor/level/burls-beets-booleans
Thank you for reporting this issue.

By the way:
I noticed that issue with self:findNearestEnemy() was fixed by Deatrix in 5th of November - and it is still pending patch :) I think that this patch can be now rejected - because it was fixed in 17th of November without patch by nwinter in issue:
https://github.com/codecombat/codecombat/issues/3166

Deatrix's Patch is in component: alliance.Allied - visible in almost every level.

**Comment by Zerrien** [comment]
ikeban,

Thanks for the contribution. I have merged your patch (as well as fixed a conflict with Deatrix's patch,) and both are now implemented. We appreciate it!
