### ISSUE TITLE
Ingame Coffeescript wrong autofill or misleading examples

### ISSUE THREAD

**Issue by vitalNohj** [codecombat/codecombat#3164]
This occurs when using the ingame code editor, and having glasses with `@distanceTo`.

When partially typing `@distanceTo` it will start predicting. When pressing enter it will fill in the rest of the code with it's prediction, which comes out to be `@distanceTo(target)`.

This may be valid Coffeescript, I'm not sure, but when hovering the mouse over the `@distanceTo target` method it shows the syntax as being `distance = @distanceTo target` and not `@distanceTo(target)`

I can see how this could confuse someone if it wasn't previously explained.

**Comment by nwinter** [comment]
Ah, right, we do this because we want the parentheses to be done correctly for you if you are going to go on to do this:

```coffeescript
if @distanceTo(target) < 10
    # ...
```

Parentheses around arguments in CoffeeScript are optional, but you would need them in this case, 'cause otherwise you would have `target < 10` as the argument to `distanceTo`:

```coffeescript
if @distanceTo target < 10
    # ...
```

At some point we can explain more about the optional parts of CoffeeScript syntax, when we have the more general programming language articles integrated into the game.
