### ISSUE TITLE
Improve ladder simulation game selection

### ISSUE THREAD

**Issue by anter69** [codecombat/codecombat#3228]
As mentioned in several threads (e.g. [here](http://discourse.codecombat.com/t/red-team-blue-team-and-fighting-self/5810/)), the opponent selection for ladder game simulation is _suboptimal_ (this is a major understatement). For example:
* fighting your own user ("red me" vs. "blue me") should be excluded (otherwise it's hard to climb to the top in both teams)

* fighting the same user several times in a row should also be excluded (e.g. accept the same player again only after 10-20 games)

![image](https://cloud.githubusercontent.com/assets/12795864/11555977/350a0190-99a4-11e5-981f-5f25b8cb31fd.png)

**update:** just to highlight the situation: on the Treasure Grove level my "red self" has a balance of 127 Wins, 73 Losses -- out of that 70 losses are against my "blue self"...

**Comment by nwinter** [comment]
I think that repeated matches against the same player should now be rarer, since the clan/course leagues thing that was making it happen is now fixed to only play you against each member of that league once when you submit. Of course, since the leagues can still be small, when other members of the league submit, they'll play you again, but that's what we want so that those league rankings are saturated.

**Comment by anter69** [comment]
Playing only once against each member may not give a really saturated result, taking into account the randomness in some arenas... but OK :smile:
