### ISSUE TITLE
Victory screen repeats reward animations on already-earned achievements

### ISSUE THREAD

**Issue by tslnc04** [codecombat/codecombat#3294]
I have only tested this in the mountain and below, but by replaying the levels and clicking submit or done, you still get the gems and xp even if it is complete.
[Before and After Pictures](http://bit.ly/1kA6t2J)

**Comment by UltCombo** [comment]
Are you sure you're getting more XP and gems? As far as I know, the victory screen repeats the unlock and "counting up" animation sequences but you don't really get any XP or gems from re-submitting a level that you have already beaten (unless you achieve an optional goal that you didn't have before).

And of course, I didn't mention repeatable levels as they are repeatable by design and unrelated to this topic.

**Comment by tslnc04** [comment]
You are right, didn't notice that the XP/Gems weren't going up.

**Comment by nwinter** [comment]
It's still a bug; it shouldn't be repeating the animations on achievements you have already earned. Changed title to reflect.

**Comment by UltCombo** [comment]
I've been seeing that bug for so long that I stopped caring at some point. But yes, it would be a great improvement to not repeat the animations for already-earned achievements.

Also, note that the XP bar (at the bottom of the victory screen) shows the amount of earned XP in an orange segment. Should this bar be updated to only display the actual amount of earned XP in orange? This would be useful for when you unlock a bonus achievement that you didn't already have.

**Comment by nwinter** [comment]
I think all of that should be working except for that the code for determining whether an achievement is new or not doesn't work any more, since now we are not loading the achievements from the server but instead telling it which EarnedAchievements we have, so [this check](https://github.com/codecombat/codecombat/blob/master/app/views/play/level/modal/HeroVictoryModal.coffee#L162-L162) fails.

**Comment by UltCombo** [comment]
@nwinter Yes, `earnedAchievement.get('created')` is undefined and `Date.parse` fails, so `completedAWhileAgo` is always false.

As far as I can see, this will require at least one new back-end query to figure out the user's previously earned achievements. Or is this information already available somewhere?

**Comment by taptapdan** [comment]
Pull request: Now checking earnedAchievementMap to determine if the achievement was previously earned.
