### ISSUE TITLE
Level FizzBuzz Path - wrong word and write error

### ISSUE THREAD

**Issue by headspeak** [codecombat/codecombat#3312]
In level description it is written silver instead of gold.

In overview body it is written hiiden instead of hidden.

**Comment by UltCombo** [comment]
> In level description it is written silver instead of gold.

They are silver coins, so I guess it is not totally wrong. Silver coins are worth two "gold", so the distinction between silver and gold depends on whether you are referring to the items or their worth.

> In overview body it is written hiiden instead of hidden.

I've fixed that and several other typos here: http://br.codecombat.com/editor/level/fizzbuzz-path
Awaiting patch review.

**Comment by UltCombo** [comment]
I've also found that the algorithm description could do with some improvement, so I've submitted another patch. I've withdrawn the previous patch and merged into the new one.

**Comment by UltCombo** [comment]
Side-note: I guess the "You are given a hint about how to route through the dungeon" phrase does not add much to the overview and could be safely removed.

I'm not sure about "be aware" or "beware", both seem correct in this context but convey different meanings.

**Comment by popey456963** [comment]
Accepted your patch @UltCombo - Good changes to the text.

I would probably stick with the be aware phrase, mostly because I'm normally aware of static objects whilst being wary of dynamic ones.  Mines being static, so would go for the former.

Gonna close this issue because it seems we've fixed most of the textual problems with this level.
