### ISSUE TITLE
Help request for possible bug with “Attack Wisely” (Kithgard Dungeon) [Python]

### ISSUE THREAD

**Issue by ghost** [codecombat/codecombat#3360]
Hi All,

Not sure if it's just me or if it's an actual bug, but I'm having trouble with "Attack Wisely" on Kithgard Dungeon using Python.

I've tried and replicated the issue twice using both Chrome (slow) and Edge (faster) and each time the same problem occurs.

I've whittled down the code to the smallest possible amount to demonstrate the bug; note this is not enough code to demonstrate the whole level, I know that:

```
# Avoid all the fire-traps
# If you step on a fire-trap, you will get blown up
self.moveUp(2);
self.attack("Door A")
self.moveUp(2)
enemy = self.findNearestEnemy()
self.attack(enemy)
self.attack(enemy)
self.attack(enemy)
```

What happens is that the character will move up, attack the door, move up again, attack once, then the code skips over as though it's not waiting for the previous code to complete. I've tried approaching this different ways and each time the result is the same; the code seems to start running rampant and skips over actions.

Is this just me or is anyone else experiencing this issue too?

Thanks in advance!

**Comment by Meerkov** [comment]
Gonna go out on a limb here and ask: If you close the browser and reload the level, does it start working? CodeCombat seems to do some storage of previous runs and sometimes it can't t

**Comment by WryZed** [comment]
It didn't at the time, but today appears to be a little different. As I say I was switching between browsers to replicate the issue myself and, at the time, was able to.

Pasting a link to the CodeCombat discourse chat I opened as a user, Hinkle, helped out by suggesting a couple of ideas, but also because I've provided a bit more detail as to what I believe may be causing the issue:

https://discourse.codecombat.com/t/help-request-for-possible-bug-with-attack-wisely-kithgard-dungeon-python/6595

**Comment by nwinter** [comment]
Should be fixed with @basicer's new Esper interpreter. Let me know if this is still broken?
