### ISSUE TITLE
Large ladder score values under the ranking histogram near edge of the container div are cropped.

### ISSUE THREAD

**Issue by Zerrien** [codecombat/codecombat#3387]
<img width="999" alt="screen shot 2016-02-08 at 1 28 33 pm" src="https://cloud.githubusercontent.com/assets/9985594/12899902/6ffde264-ce68-11e5-8f01-fce17003c158.png">
<img width="489" alt="screen shot 2016-02-08 at 1 32 34 pm" src="https://cloud.githubusercontent.com/assets/9985594/12899905/715dcc28-ce68-11e5-9420-f367c12b9cbd.png">

LadderView/LadderTabView are good places to start looking.

**Comment by teplyja1** [comment]
I will try to fix that.

**Comment by teplyja1** [comment]
I think i have a solution. It works great in JsFiddle but i am not able to test in my local instance of CodeCombat, because accessing ladder tabs returns 404, i think its because ladder data is not i my local database. Could you please advice some solution?

Code of the fix can be seen here : https://jsfiddle.net/TeplyHonza/gz17grkm/

**Comment by nwinter** [comment]
Hey @teplyja1, thanks for taking a look at that! I went to test your solution, which is very comprehensive, but found that a quick CSS hack seemed to the trick just as well, so I went with that instead.

**Comment by teplyja1** [comment]
Hi, ok.
Nice and easy solution.
I will have a look at something else.

**Comment by nwinter** [comment]
Okay, cool. I would really like your solution if we didn't have random extra overflow space we happen to be able to use in this design, so if we update it, I'll look back at how you were pulling those calculations off.
