### ISSUE TITLE
Add "maximize code editor" button to levels

### ISSUE THREAD

**Issue by anter69** [codecombat/codecombat#3400]
Add the "maximize/minimize code editor" button to campaign levels. It's already available in the courses:

![image](https://cloud.githubusercontent.com/assets/12795864/13045233/71563912-d3d2-11e5-9513-554e484229bb.png)

It's probably not necessary for the dungeon and forest levels, but starting from the desert it should be present.

**Comment by nwinter** [comment]
Code is [here](https://github.com/codecombat/codecombat/blob/master/app/templates/play/level/tome/spell_list_tab_entry.jade#L21-L24):

```jade
  if levelType !== 'hero' && levelType !== 'hero-ladder' && levelType !== 'hero-coop'
   .btn.btn-small.btn-illustrated.fullscreen-code(title=maximizeShortcutVerbose)
     .glyphicon.glyphicon-fullscreen
     .glyphicon.glyphicon-resize-small
```

I guess this was originally because I didn't want it to show up as clutter on the beginner levels, back when the hero campaign was new. Now that we have levels with type `course` and `course-ladder`, the button happens to show up there. We should probably have something based on player level (`me.level()`) instead.

Want to throw down a pull request?

**Comment by DeanWay** [comment]
Would it be a good idea to have one of the yellow arrows pointing to the button when it is first added?

**Comment by nwinter** [comment]
Yup!

**Comment by anter69** [comment]
The issue can be closed -- the button now appears as expected. Thanks for everyone contributing! :+1:
