### ISSUE TITLE
Purchasing enrollments is done using unsecure connection

### ISSUE THREAD

**Issue by sebekz** [codecombat/codecombat#3554]
When purchasing enrollments for a new student, the page stays at HTTP, instead of explicitly switching to SSL secure connection. This creates confusion and may lead to abandoned purchase process. Credit card details should only be given over a secure SSL connection.

**Comment by UltCombo** [comment]
IIRC CodeCombat delegates all the purchases to the [Stripe](https://stripe.com/) payment system, which opens in a completely isolated HTTPS `iframe`. That is, the information you are inputting into it is completely safe, encrypted and isolated from the embedding environment, but the browser will not display the green lock in the location bar as the payment system is inside an iframe instead of the top frame.

So, in practice there is absolutely no difference whether CodeCombat is running over HTTPS or not—your browser will communicate with the Stripe servers for the negotiation, not CodeCombat's—but I agree that users would feel more comfortable if the payment pages were running on HTTPS to display the green lock icon in the location bar (again, though, this would be mostly an aesthetic appeal in this case).

Thinking a bit further, though, it *may* be possible to tamper with the CodeCombat page through DNS poisoning or such and alter the Stripe parameters to direct the payment to a hacker. Running CodeCombat over HTTPS would greatly help preventing this kind of attack.

**Comment by sebekz** [comment]
The thing is, the customer does not know any of that and is not aware of the fact, that there is a secure ```iframe``` involved. One would need to use Fiddler, browser dev tools or any other similar tool to inspect network traffic and even then, it would not be a trivial task to check the certificate being used to encrypt the traffic.

I understand aesthetics behind the decision but I don't agree that it's only that. Being able to visually inspect that the connection is indeed secure, be able to quickly look at the certificate - it's crucial to more and more people when they make purchase. And I would guess that CodeCombat customers are more on the tech side than an average customer on the web. In favor of a nice looking UI the UX is ruined and my guess is that your conversion rate is affected as well. A quick hotfix for the issue would be a short textual explanation in fine print on the CC enter page.

**Comment by nwinter** [comment]
We should probably be smart about when we can switch the user to using `https` sitewide and do that when available. I haven't looked into it, though. See also #3415 and #2505.

**Comment by UltCombo** [comment]
@nwinter From reading your linked issues, it seems that we are just waiting for `analytics.codecombat.com` to support HTTPS and then we can enable HTTPS-by-default in the whole site. That will fix any current and future issues regarding insecure purchasing and login.

**Comment by basicer** [comment]
codecombat.com is now HTTPs all the time.
