### ISSUE TITLE
Math:atan2() not working for Lua

### ISSUE THREAD

**Issue by promi** [codecombat/codecombat#3768]
The level is "Bombing Run"

This works, the hero says "90" and the bombers do an attack run in the 90 degrees direction:
```
loop
    local enemy = hero:findNearestEnemy()
    if enemy then
        self:say(90)
    end
end
```

This works (like the above):
```
loop
    local enemy = hero:findNearestEnemy()
    if enemy then
        local angle_radians = 0.5 * Math.PI
        local angle_degrees = angle_radians * (180 / Math.PI)
        self:say(angle_degrees)
    end
end
```

This does not work at all, the hero says nothing, but curiously the attack run goes in the 360 degrees direction:

```
loop
    local enemy = hero:findNearestEnemy()
    if enemy then
        -- Should be near 0.5 * Math.PI, but seems to be NaN or something?!
        local angle_radians = Math:atan2(22, 7)
        local angle_degrees = angle_radians * (180 / Math.PI)
        self:say(angle_degrees)
    end
end
```

It seems like Math:atan2() is not implemented at all for Lua?

**Comment by basicer** [comment]
`Math:atan2` is the incorrect invocation in lua. It should be `math.atan2`.  Using the : operator won't work because it will send `math` as the first argument when the y-cord is expected.  See https://www.lua.org/pil/16.html

In lua proper you would get a better error message here that a number was expected instead of a table for the first argument.  However lua2js just exposes the javascript Math object directly.

**Comment by promi** [comment]
Ok, but then the documentation in the Grammaticon V is incorrect. Also why the strange behavior of the game? There should at least be some error message ...
