### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [codecombat/codecombat#3775]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like codecombat, deleted the software history during the transition to open-source.

https://github.com/codecombat/codecombat/commit/6009df26de7c7938c0af2122ffba72c07123d172

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask codecombat developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by nwinter** [comment]
1. We were trying to make the repository as small as possible so that it would be easier for contributors to check out initially, and there were some large files in the history. This way we also didn't have to worry about whether all the files in all the old versions were legal to open source.
2. The old history is still there in a private repo that we can check if we need to. I have never had to refer to it, though.
3. Not sure; I never heard about it, anyway. I think most of the new developers were less interested in workflows like "a bug has appeared, let me see what changed and what was the original reason for changing this piece of code" and more interested in things like "I need to add a new feature, where should I put it?", which relies much less on checking history.
4. If we didn't have the old repo, it wouldn't be possible to go back and view the earliest days of the project, so we wouldn't be able to satisfy our curiosity–but we just moved to a new repo, we didn't delete the history out of the old one.

Hope this helps!

**Comment by gustavopinto** [comment]
Hi @nwinter, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
