### ISSUE TITLE
Have I spotted an Error or am I completely missing something?

### ISSUE THREAD

**Issue by PrimeTimeTran** [codecombat/codecombat#3956]
I might simply not know JS...
I've been playing around in code combat to learn some javascript and I can't seem to understand what I've done wrong.

Thus far in the levels each statement moves the hero to the dot on the stage, however this time he keeps going and doesn't execute the following up, left, and then down statements...
Here's a video to show you what I mean.
http://www.youtube.com/watch?v=D-2CYy3Vz5g

I tried running it without the while loop but he still continues going right into the wall and doesn't follow the following three statements.

**Comment by themaka** [comment]
Hi there!
You're overthinking it a bit. On that level, we're just trying to explain that block code needs {} around it. All you need to do is add them. You don't need to reproduce the entire block plus the {}.

It repeats the moveRight(); command because of an obscure JS rule where you don't need the {} for a single-line block code.

**Comment by PrimeTimeTran** [comment]
@themaka aww your 100% right. My bad.

I'm in a dark room with my screen brightness turned down low and I not very familiar with JS so I didn't realize the brackets were commented out. Thanks bro.
