### ISSUE TITLE
ladder is too slow (few games + badly chosen opponents + illegal scoring)

### ISSUE THREAD

**Issue by vn971** [codecombat/codecombat#4096]
The problem consists of many parts, all of them leading to a poor AI developer experinence:

* First, there are too few games played. I've submitted my AI 4 days ago, and even though it's TOP 50 (or better), it only played one game so far. 1 win, 0 losses for 4 days.  (EDIT: 4 days with one game already.)

* There are players whose code is incorrect for more than a year, and they are still in TOP-10 (one of them is TOP-1, see https://codecombat.com/play/ladder/multiplayer-treasure-grove#ladder

* opponents are chosen badly. So far my AI (blue team, player "heavy") has played 61 games, winning all of them. Yet, it's still only TOP-60, because the server did not assign strong enough opponents for my AI. (I know they exist because some of the TOP-10 actually beat me, as I've observed locally.) Anyway, the problem is that the server does not assign players with relatively the same strength as my AI is, but it should.

Note: I'm simulating a lot recently, about 30k games were simulated in the last days. It probably helps, but things are still bad (see 1-st problem).

**Comment by vn971** [comment]
Offtopic: psychology studies say that people are most enthusiastic to improve some skill if they have about 50% of successes/failures (solved or not problems from a collection, wins/losses etc). Addressing the 3-rd problem I wrote could actually make the ratio closer to 50% for lots of the player, which _could_ (I'm obviously speculating) improve the interest for the users.

**Comment by nwinter** [comment]
We just happened to be discussing another strategy for this in Slack, so I'll save that discussion here, too:

danny: I was just looking at codecombat/server/queues/scoring/getTwoGames.coffee to try to understand how simulations are done better.  How is this interpretation:

1. Try to do a match against players that are in the same clan as the simulator first, failing that, do a match amongst any players.
2. Select 2 sessions to match against each other.
   a. One will be weighted toward recent submissions
   b. Other will be random of all matches
   c. Randomly choose which side will be which (edited)

danny: Questions I have.  Would it be resource efficient to have the selections for the sessions to be:
1. Select 'humans' or 'ogres' at random.
2. From the side selected, randomly select from sessions that don't have at least 200 matches played.
   a. If all have at least 200 matches, select a random session weighted toward recent submissions.
3. From other side randomly select from all, but weighted toward sessions that have had the longest time since last simulation.
   a. If these 2 have a result already, if so, return to step 3.
   b. If ten attempts have been made and all are repeats, default to just random against random.

nick: unfortunately we would need to create new database index fields for steps 2 and 3

so something like that is possible now with Mongo 3.4, but would take a long time to reconfigure

I wonder what the perfect simulation system would be. If we are going to do a large changes to it, I’d want to get big bang out of it. The scheme you proposed fixes part of the problem, but doesn’t fix the human vs. ogre imbalance problem, doesn’t do anything to help people simulate the matches they care about seeing results for now, and doesn’t help simulate against the AI opponents

danny: I'd love to see a way that a user could target a specific player to get a simulation done for that battle.  Of course, we'd need to do some checking so they couldn't just find a bunch of players that they beat and only target them in order to increase their rank.

OK, so what if first stage of simulation for all sessions is to make their way up the AI opponent list until they fail to beat an AI, then the session is ranked against others that have matched the same number of AIs.  So if I can't beat the first AI, my random matches are only against others that can't be the first AI.  Then the rankings would be based off of which AI was defeated first, then off of performances against other opponents.

nick: mm, interesting approach
brings back some of the complexities of a multi-stage process, but if we rewrite most of this logic in a more modern architecture, maybe none of this has to be so complicated that it couldn’t work
could merge that with the original Bayesian ranking thing that Michael had put together for playing opponents around your skill level

danny: I guess then, when you submit for ranking, you should fairly quickly be able to see what tier you are in.  I assume that could be stored to the database and retrieved when picking matches.

**Comment by vn971** [comment]
Thanks. Ok, I think the first problem one has to answer is -- what exactly are we trying to fix?
Things I know of:
* outdated info, like the top1 player's AI not compiling.
* show the player both great AIs and weak ones, to have a bigger picture, not give up etc. I would personally say 30-70% win percent is a valid goal.
* show non-obvious opponents and tactics. Obviously, that's complex. Maybe selecting "contradictory" players will help (those with unstable rank that can beat stringer gyus/gals but loose to weaker).
* make rank determination fast. Less games to get a good estimate. Less time for the player to wait.
* Reduce server load. Players with good-enough estimations should be less engaged. Some other things to consider here?

To be continued...
-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by vn971** [comment]
I won't suggest very concrete algorithms, but something among the line of those algos could work:

* for 2,4 -- try to assign big part of the games with relatively similar opponents. For example, just pick a number following a normal distribution around hero-s own strength, and take the opponent closest to the chosen value.

* for 1, reset statistics (by rolling model or instantly) because of non-compatible code format. This way the visible list of TOP AI algorithms will actually contain good code that one can fight against. Yeah, it feels bad for the "old heroes", but the reason is code incompatibility anyway, not outdated statistics.

* for the 7 part, the server could send a clique (as in graph theory and social sciences) of players for simulating, and expect the client to return the results of each player playing against each other. This way, the server will have less outgoing traffic, maybe less incoming traffic (if the client can send it in pack), and the client can reuse parts like code transformation (if there is such a step at all). Maybe in practice this thing is of little importance, IDK.

Thoughts? Questions?

**Comment by vn971** [comment]
EDIT: added another case --^

**Comment by nwinter** [comment]
@schmatz what do you think–how would you do it today?

**Comment by schmatz** [comment]
Will think about it and get back to you.

**Comment by vn971** [comment]
@schmatz thanks! It'd be cool to address some of those problems.

**Comment by nemoyatpeace** [comment]
So glad this is getting some traction again.  All I want for Christmas is an improved ladder system!

**Comment by nwinter** [comment]
Fixed in https://github.com/codecombat/codecombat/commit/3067260b09c434d952d24cb7c1253efb0d4ccc06
