### ISSUE TITLE
[BR-Localization] Spelling Errors on the BR-Homepage, Feature Spread Row and more.

### ISSUE THREAD

**Issue by cwmaia** [codecombat/codecombat#4298]
When the user accesses the CodeCombat site from a IP in Brazil, there are several issues with the localization. There are also places on the Modes for the Start Now section that are not localized.

1: Words mispelled: Estrurutura,Toodos
2: Grammar could be improved for Br-Portuguese
3: Comece com seus Alunos Hoje should read Comece a Ensinar ou Estudar Hoje!
4: Dropdown with Schooling Levels needs to be localized.
5: Description for the Courses need to be localized as well as some CSS issues addressed.

![homebannerspelling](https://cloud.githubusercontent.com/assets/1056740/25246833/4c371c90-25df-11e7-946d-80262571a482.png)
![homebannergrammar](https://cloud.githubusercontent.com/assets/1056740/25246830/4c34447a-25df-11e7-8692-ed38754285d7.png)
![startnow-changetext](https://cloud.githubusercontent.com/assets/1056740/25246832/4c35c5ac-25df-11e7-8a69-50b08705052d.png)
![localizationbugs1](https://cloud.githubusercontent.com/assets/1056740/25246831/4c349470-25df-11e7-8c04-e3c810cef823.png)
![modeslocalization](https://cloud.githubusercontent.com/assets/1056740/25246829/4c31301e-25df-11e7-9998-6e23a90ac4bc.png)

**Comment by nwinter** [comment]
1, 2, 3, and 4 were fixed by #4375 by @fernandaagr.

For 5, you can translate the courses here:
1. https://direct.codecombat.com/i18n/course/introduction-to-computer-science
2. https://direct.codecombat.com/i18n/course/game-development-1
3. https://direct.codecombat.com/i18n/course/web-development-1
4. https://direct.codecombat.com/i18n/course/computer-science-2
5. https://direct.codecombat.com/i18n/course/game-development-2
6. https://direct.codecombat.com/i18n/course/web-development-2
7. https://direct.codecombat.com/i18n/course/computer-science-3
8. https://direct.codecombat.com/i18n/course/computer-science-4
9. https://direct.codecombat.com/i18n/course/computer-science-5
10. https://direct.codecombat.com/i18n/course/computer-science-6

For the text overflow, any way we could shorten "Desenvolvimento de Game 1"? In English we could shorten from "Game Development" to "Game Dev", maybe something similar would be understood?

**Comment by cwmaia** [comment]
Fixed and Closed.

**Comment by fernandaagr** [comment]
Translation and necessary changes made in 5.
