### ISSUE TITLE
Have you guys given up the Codecombat-iOS project?

### ISSUE THREAD

**Issue by scris** [codecombat/codecombat#4572]
I want to know.
Merci!

**Comment by nwinter** [comment]
It's on the backburner. We got it to the stage where it was accepted to the App Store, and solved the problem of typing code on iPads, but it needed a lot of polish and performance improvements to really be good. I'd love to be able to continue it, but we would need some help in order to keep up with that many platforms. At some point we will pick it up again, but can't say when.

Is CodeCombat on iOS something you'd be interested in helping out with?

**Comment by chrisgomez423** [comment]
How about Android ill be interested in that

**Comment by nwinter** [comment]
We'd likely prototype everything on iOS first, and possibly do native Android later, although it may be possible to better support Android with some tweaks to the web version much sooner if there are specific annoyances we can remove currently to make code editing and the UI work better. In general, phone-sized layout is going to be a much bigger project than getting things working on tablets, and for tablets we see iPad as the first target.

**Comment by chrisgomez423** [comment]
Cool if you guys get started on one of them soon I'm interested in it
