### ISSUE TITLE
API tests?

### ISSUE THREAD

**Issue by vn971** [codecombat/codecombat#4780]
Some time ago, I saw `loop { ... }` construct being available (and working) in javascript. I used it (wasn't sure if it provides some perf advantage). A couple of days later though, it started being a syntax error.

Is it possible to cover some of such "regressions" by tests? The goal is to not break older code submissions with API changes.

**Comment by nwinter** [comment]
We deprecated `loop` syntax a couple years ago (we used to use that so that `while (true)` loops wouldn't infinitely loop if there were no blocking actions in it, but then we figured out how to yield for one frame iff no actions were taken even within normal `while (true)` loops), just finally updated our parser to remove support for it.

We do have an internal tool to test solutions on all published levels to make sure the outcomes are the same when we make changes like this. I was comfortable dropping `loop` support in this case given how long ago we switched.

**Comment by vn971** [comment]
I see, no prob then.
