### ISSUE TITLE
Proposal: Need additional English word explanations for students

### ISSUE THREAD

**Issue by JaewonLee0217** [codecombat/codecombat#5690]
Problem

I think Code combat is a project aimed at students not only learning programming but also getting used to coding and the computer languages. But considering for lower grade students who are not good at English or don't know English at all, i think it will not be effective to them.

Proposal

I think the additional explanation of the word that including functions or methods should be added when playing games(coding) for students who are not familiar with English. For example, when we use "character.MoveRight()", it needs an additional explanation like "[character: translating for this word, Move: translating for this word, Right: translating for this word]"( words: translation for each lanaguage).

In the end, I expect if you add the translations of English words that used functions or methods,
I hope that adding a translation of English words will help us understand the coding and better meet the goals of this project, as well as help us learning English.

**Comment by nwinter** [comment]
We do have those glosses in when the translations are available. See this example for Chinese:
<img width="1498" alt="Screenshot 2019-11-28 14 42 55" src="https://user-images.githubusercontent.com/99704/69834136-6523fc80-11ed-11ea-85aa-784f888e3530.png">

Let me know if you think of a more appropriate place for these glosses. Otherwise, we rely on open source volunteers to add these kind of translations using the /i18n editor: https://codecombat.com/i18n
