### ISSUE TITLE
Translation workflow

### ISSUE THREAD

**Issue by PatrickMassot** [codecombat/codecombat#5816]
Probably among many other people, I'd like to use the virus lock-down opportunity to teach some coding skills to my children (so this issue is somewhat urgent). CodeCombat looks like a very nice project, but unfortunately it's currently unusable for French kids, because even the first Kithgard Dungeon levels are only half translated ([this thread](https://discourse.codecombat.com/t/translation-french-standards/3452) and similar ones suggest there was some effort in 2015, but everything added after that date appears in English, including all articles before I started on them yesterday).

So I'd like to help with translations but, as far as I can see, the translation process is extremely tedious, and it looks like one developer-day (or probably less) could make it immensely better. Maybe I missed some entry points, and then this issue becomes a documentation issue.

Currently [this page](https://codecombat.com/contribute/diplomat) is very easy to find, altough it starts with a [dead link](http://blog.codecombat.com/post/64658141307/codecombat-in-y-combinator). But most of the page is about the locale files on GitHub that are both technical to edit (needing some GitHub skills) and mostly done. The important bit is completely lost in the middle, it's the link to https://direct.codecombat.com/i18n, which should be the Huge **bold** link.

Unfortunately that link leads to a page that is a very long and messy list. One extremely easy improvement would be to allow filtering by type, together with a link to explanations of the various types. The "Specifically covered" column is also a total mystery to me. Does it mean "Done"? It looks like some translated files have No in this column. It would be much better to have a column "Status" containing stuff like "80% done" (simply counting the number of translated item, no need for a precise measure).

But really the huge improvement here would be able to filter by campaign. Having the Kithgard dungeon done would already mean we can direct thousands of kids to this game. I tried to update the first few levels, but this needs finding the English names of the level by playing the game (or else I couldn't find the relevant information somewhere easier). Even articles and other types should appear by campaign, not only levels (this should be an easy database request away).

Something else that is completely unclear to me is the relation between the translations we can write in the level editor at https://codecombat.com/editor/level/ vs the translation in the translation site at  https://codecombat.com/i18n/level. Should we edit both? Should we use only the second link and the first one will get updated automatically?

All the above seem trivial to implement. Something that would be *very* worthwhile but probably more difficult would be to track duplicated messages. Many translatable strings appear again and again. Currently it seems there is no help for translators to ensure consistency of translations. Each time https://codecombat.com/i18n/ displays a string to translate, it could search the database for other appearances of this string that have already been translated, and display the corresponding translations (with links to the translation pages where they appear).

Another thing that would probably require dev effort would be to keep track of modification times. Basically, the i18n website should flag every string whose English version has been modified after it had been translated. Yesterday I clearly retranslated stuff that was outdated (or else the original translator was crazy).

Finally I don't understand why new articles appear instantly in the live game while level translations are stuck in some kind of review process. I don't complain the review takes too long, I edited stuff yesterday, but I think it would make sense to publish updates by default, and review after the fact, as on Wikipedia. Did you encounter abuse? If yes then why are the article published instantly?

**Comment by codeluggage** [comment]
This is a fantastic list of issues, @patrickmassot! Thank you for compiling this. 

We are starting a big overhaul, and translations are part of that. The documentation on how to help with will be updated, the outdated information will be removed, and we are allocating time to merge and resolve PR's so translations can be included. 

Let me address each point in order, too: 

* That is indeed a dead link. There may be more of these, since the blog structure changed. This is the new link: https://blog.codecombat.com/codecombat-in-y-combinator/ - I'll also update this on the Diplomat page itself. 
* The i18n page is painful to work with, and we have recently discussed potential improvements we could make. 
* I've asked for more details on the "Specifically Covered" column, but as far as I can tell in the moment it has to do with languages that have overlap. Specifically covered means that there is a translation for exactly that locale. 
* Campaign filtering is a great idea! I think this could really help clarify what each piece of translation belongs to. It may not be simple to extract this information, we'll see. 
* The question about https://codecombat.com/editor/level/ vs https://codecombat.com/i18n/level looks to simply be overlap. i18n/level is a simplified way of doing it. 
* Duplication checks can be tricky, especially because context matters in many situations and for many languages. It still sounds useful to display duplicates, though.
* We don't have specific timestamps for when translations were last updated, but it could be added. It's hard to say how useful it would be when added now, compared to always being tracked. 
* This has to do with preventing abuse yes, but there are inconsistencies.

Your insight on this is very useful, thank you! I've surfaced all these suggestions to the team for prioritization.
