### ISSUE TITLE
Block coding support (Blockly)

### ISSUE THREAD

**Issue by txomon** [codecombat/codecombat#6248]
I have been trying to hook the kids into codecombat for a while, and although they did some progress at the beginning, all the required writing made the bar too high for the 7y/o and too cumbersome for the 9y/o. I have started to introduce them to code.org's coding platform, and realised that the backend they use, blockly https://developers.google.com/blockly can be easily integrated in codecombat.

It would also allow for side to side display of blocks and code for the interested ones. Is there any plans on supporting block based programming?

**Comment by nwinter** [comment]
I do want to experiment with it further, since it would be great to add some beginner content to go along with it as well as making it an option for the rest of the levels, opening it up to more players and better support on iPad with no need for virtual keyboard. We did a test integration a long time ago in the https://github.com/codecombat/codecombat/tree/blocks branch and it seems like it will work fine, just takes some doing. Welcome to further open source contributor experiments before our core team has a chance to get to it.

**Comment by nwinter** [comment]
This is now in for CodeCombat Junior. As we improve support for it, we will make it more available for core CodeCombat levels as well.
