### ISSUE TITLE
Cell Commentary (Red) Not available

### ISSUE THREAD

**Issue by jan-koupil** [codecombat/codecombat#6538]
I introduced the game to my students, however they found out, that they can complete only the first 5 levels. Cell commentary (the 6th one) requires payment now, even though it is a red flag.

It is interesting that on older accounts where the level was finished previously, it can be started without no problem

If it is not a bug, then it means the game is not free to play, but only has an extremely short demo.

**Comment by Chaboi45** [comment]
Right. A few months ago CodeCombat limited free levels to 5 levels.

**Comment by nwinter** [comment]
@jan-koupil if you have students, you should be using the classroom version of CodeCombat by creating a teacher account and inviting them to your classroom to create student accounts. That will let you get the first course of the classroom version, Computer Science 1, for free (roughly equivalent to the dungeon world). For more content outside the first free course, our school support team would be happy to talk about whether the paid licenses could meet your needs–you can contact them at [schools@codecombat.com](mailto:schools@codecombat.com).

The home/individual version is for players playing on their own, outside the context of a school or teacher’s classroom. We are adjusting the amount of free levels in that version for new accounts in order to be able to support our business, trying to figure out the best balance between providing free learning opportunities and being able to sustainably provide the service.

**Comment by maguszoldik** [comment]
My wife begins to learn coding. I encourage her to go in your game, that I tried years ago and was cool, with pretty good french support.
Sadly, the game blocks her after only 5 levels, asking to pay. My old account does not seems to have this restriction.
On your Premium page, it is stated that Premium give access to 531 more levels. You should clearly state that only the 5 first levels are accessible.

And come on, only 5 levels??? How can someone have a good glimpse of what you have to offer?
