### ISSUE TITLE
I would like to translate all dynamic content into Japanese at once using ChatGPT.

### ISSUE THREAD

**Issue by kamome-run** [codecombat/codecombat#6972]
Good evening.

I would like to translate all dynamic content into Japanese, 
but it takes too much time with [i18n pages](https://direct.codecombat.com/i18n) .

I would like to use ChatGPT to do the translation all at once, 
just like translating static content, any ideas?

**Comment by tsubame-kamome** [comment]
AI + human, I like it! In my case, I have the AI do the translation, then I review and correct it with my own eyes.

I'm using GPT-4!

When I translate from English to Japanese, I can tell at a glance that the translation needs to be reworked by a human because the nuance will inevitably be strange if the translation is done by an AI.

**Comment by nwinter** [comment]
We have added AI translations for just about everything. In the i18n system, you can now see [AI_TRANSLATION] tags, and can do the human edits off of that base if anything needs tweaking.

**Comment by kamome-run** [comment]
@nwinter Thank you so much!
